import { DarkAppColors } from "./DarkAppColors";
import { LightAppColors } from "./LightAppColors";
import { SystemTheme } from "./SystemTheme";

/**
 * Copyright (c) 2023-2026 SolisWare.
 * 
 * All rights reserved. Licensed under the MIT license.
 * See the LICENSE.txt file in the project root directory for details.
 */
export const AppColors = {
  LIGHT: LightAppColors,
  DARK: DarkAppColors,

  
  // Add New note Tile
  NEW_NOTE_BG: "#F2F7FF",
  // Toolbar
  TOOLBAR_BACKGROUND: "#FEFEFE",
  TOOLBAR_TOP_BORDER: "#F1F3F5",
  TOOLBAR_BOTTOM_BORDER: "#E8EAED",
  TOOLBAR_TEXT: "#1F2933",
  TOOLBAR_BUTTON_BACKGROUND: "#FFFFFF",
  TOOLBAR_BUTTON_BORDER: "#E8EAED",
  TOOLBAR_BUTTON_DISABLED_BACKGROUND: "#FBFBFC",
  TOOLBAR_BUTTON_DISABLED_TEXT: "#B7BEC7",
  TOOLBAR_BUTTON_DISABLED_BORDER: "#E7EAEE",
  TOOLBAR_BUTTON_HOVER_BACKGROUND: "#EFF8F2",
  TOOLBAR_BUTTON_HOVER_TEXT: "#14523B",
  TOOLBAR_BUTTON_HOVER_BORDER: "#BCDCCB",
  TOOLBAR_DELETE_BUTTON_HOVER_BACKGROUND: "#FFF5F5",
  TOOLBAR_DELETE_BUTTON_HOVER_TEXT: "#B42318",
  TOOLBAR_DELETE_BUTTON_HOVER_BORDER: "#F3C7C7",
  // Toolbar - Dark
  TOOLBAR_BACKGROUND_DARK: "#2A2A2A",
  TOOLBAR_TOP_BORDER_DARK: "#353535",
  TOOLBAR_BOTTOM_BORDER_DARK: "#9A9A9A",
  TOOLBAR_TEXT_DARK: "#F5F7FA",
  TOOLBAR_BUTTON_BACKGROUND_DARK: "#343434",
  TOOLBAR_BUTTON_BORDER_DARK: "#474747",
  TOOLBAR_BUTTON_DISABLED_BACKGROUND_DARK: "#2E2E2E",
  TOOLBAR_BUTTON_DISABLED_TEXT_DARK: "#98A1AB",
  TOOLBAR_BUTTON_DISABLED_BORDER_DARK: "#404040",
  TOOLBAR_BUTTON_HOVER_BACKGROUND_DARK: "#39423F",
  TOOLBAR_BUTTON_HOVER_TEXT_DARK: "#E3FFF4",
  TOOLBAR_BUTTON_HOVER_BORDER_DARK: "#55655F",
  TOOLBAR_DELETE_BUTTON_HOVER_BACKGROUND_DARK: "#5B3035",
  TOOLBAR_DELETE_BUTTON_HOVER_TEXT_DARK: "#FFD7D7",
  TOOLBAR_DELETE_BUTTON_HOVER_BORDER_DARK: "#8A4C54",
  // MISC
  DISABLED_TEXT: "#B0B0B0"
}

export const getAppColors = (theme: SystemTheme) => {
  return theme === SystemTheme.DARK ? AppColors.DARK : AppColors.LIGHT;
}
