/**
 * Copyright (c) 2026 SolisWare.
 * 
 * All rights reserved. Licensed under the MIT license.
 * See the LICENSE.txt file in the project root directory for details.
 */
export const DarkAppColors = {
  // App's Primary color palette.
  MAIN_LIGHT: "#4AA3D1",
  MAIN: "#2A7CA5",
  MAIN_DARK: "#1F5C79",
  MAIN_TEXT: "#F5F7FA",
  // App's Secondary color palette.
  SECONDARY_LIGHT: "#4E8E76",
  SECONDARY: "#2F6C57",
  SECONDARY_DARK: "#244F41",
  SECONDARY_TEXT: "#F5F7FA",
  // App's accent color.
  ACCENT: "#182129",
  // App's error color.
  ERROR: "#C84B5A",
  ERROR_LIGHT: "#E58A97",
  ERROR_LIGHT_BACKGROUND: "#E58A971F",
  DISABLED_TEXT: "#B0B0B0",
  // Note
  NEW_NOTE_BG: "#F2F7FF",
  NOTE_TEXT: "#FCFDFE",
  NOTE_PLACEHOLDER_TEXT: "#D6DEE6",
  NOTE_FOOTER_TEXT: "#BCC6CF",
  NOTE_DELETE_BUTTON_COLOR: "#C4D0D9",
  NOTE_DELETE_BUTTON_HOVER_TEXT: "#F2C3CB",
  NOTE_DELETE_BUTTON_HOVER_BACKGROUND: "#5A303A",
  // Toolbar
  APPBAR_BACKGROUND: "#1E4256",
  APPBAR_TEXT: "#F5F7FA",
  TOOLBAR_DELETE_BUTTON_HOVER_BACKGROUND: "#5B3035",
  TOOLBAR_DELETE_BUTTON_HOVER_TEXT: "#E3FFF4",
  TOOLBAR_DELETE_BUTTON_HOVER_BORDER: "#8A4C54",
  WINDOWS_TOOLBAR_BACKGROUND: "#2A2A2A",
  WINDOWS_TOOLBAR_TOP_BORDER: "#303030",
  WINDOWS_TOOLBAR_BOTTOM_BORDER: "#383838",
  WINDOWS_TOOLBAR_TEXT: "#F5F7FA",
  WINDOWS_TOOLBAR_BUTTON_BACKGROUND: "#343434",
  WINDOWS_TOOLBAR_BUTTON_BORDER: "#474747",
  WINDOWS_TOOLBAR_BUTTON_DISABLED_BACKGROUND: "#2E2E2E",
  WINDOWS_TOOLBAR_BUTTON_DISABLED_TEXT: "#98A1AB",
  WINDOWS_TOOLBAR_BUTTON_DISABLED_BORDER: "#404040",
  WINDOWS_TOOLBAR_BUTTON_HOVER_BACKGROUND: "#39423F",
  WINDOWS_TOOLBAR_BUTTON_HOVER_TEXT: "#E3FFF4",
  WINDOWS_TOOLBAR_BUTTON_HOVER_BORDER: "#55655F",
  WINDOWS_TOOLBAR_DELETE_BUTTON_HOVER_BACKGROUND: "#5B3035",
  WINDOWS_TOOLBAR_DELETE_BUTTON_HOVER_TEXT: "#FFD7D7",
  WINDOWS_TOOLBAR_DELETE_BUTTON_HOVER_BORDER: "#8A4C54",
  TOOLBAR_VARIANT_OUTLINE: "#44667A",
  TOOLBAR_VARIANT_HOVER_BACKGROUND: "#234F3F",
  TOOLBAR_VARIANT_HOVER_OUTLINE: "#4D7B69",
}
