/**
 * Copyright (c) 2026 SolisWare.
 * 
 * All rights reserved. Licensed under the MIT license.
 * See the LICENSE.txt file in the project root directory for details.
 */
export const LightAppColors = {
  // App's Primary color palette.
  MAIN_LIGHT:      "#3CBBEB",
  MAIN:            "#138EC7",
  MAIN_DARK:       "#127DB3",
  MAIN_TEXT:       "#FFFFFF",
  // App's Secondary color palette.
  SECONDARY_LIGHT:  "#52BE8F",
  SECONDARY:        "#00A362",
  SECONDARY_DARK:   "#009557",
  SECONDARY_TEXT:   "#FFFFFF",
  // App's accent color.
  ACCENT: "#F0F7FA",
  // App's error color.
  ERROR: "#E60000",
  ERROR_LIGHT: "#FF9999",
  ERROR_LIGHT_BACKGROUND: "#FF999914",
  // Note
  NOTE_TEXT: "#1F2933",
  NOTE_PLACEHOLDER_TEXT: "#7B8794",
  NOTE_FOOTER_TEXT: "#4F5D6B",
  NOTE_DELETE_BUTTON_COLOR: "#138EC7",
  NOTE_DELETE_BUTTON_HOVER_TEXT: "#E60000",
  NOTE_DELETE_BUTTON_HOVER_BACKGROUND: "#FF999914",
  // Toolbar
  TOOLBAR_BACKGROUND: "#FEFEFE",
  TOOLBAR_TOP_BORDER: "#F1F3F5",
  TOOLBAR_BOTTOM_BORDER: "#E8EAED",
  TOOLBAR_TEXT: "#1F2933",
  TOOLBAR_BUTTON_BACKGROUND: "#FFFFFF",
  TOOLBAR_BUTTON_BORDER: "#E8EAED",
  TOOLBAR_BUTTON_DISABLED_BACKGROUND: "#FBFBFC",
  TOOLBAR_BUTTON_DISABLED_TEXT: "#B7BEC7",
  TOOLBAR_BUTTON_DISABLED_BORDER: "#E7EAEE",
  TOOLBAR_BUTTON_HOVER_BACKGROUND: "#EFF8F2",
  TOOLBAR_BUTTON_HOVER_TEXT: "#14523B",
  TOOLBAR_BUTTON_HOVER_BORDER: "#BCDCCB",
  TOOLBAR_DELETE_BUTTON_HOVER_BACKGROUND: "#FFF5F5",
  TOOLBAR_DELETE_BUTTON_HOVER_TEXT: "#B42318",
  TOOLBAR_DELETE_BUTTON_HOVER_BORDER: "#F3C7C7",
}
